---
title: "imcRtools analysis of the Pancreas dataset"
author: "Bruno Palau"
date: "`r Sys.Date()`"
output: html_document
---

#Quantify Interactions between celltypes in breast cancer tissue to use it in generative model

##import libraries and breast cancer single cell experiment
```{r,include=FALSE}
library(MASS)
library(ComplexHeatmap)
library(imcdatasets)
library(imcRtools)

library(scales)
library(viridis)
library(circlize)

sce <- JacksonFischer2020Data(data_type = "sce")
```

##subset and build spatial graph
```{r}
#use 8 neighbors to simulate nearest 8 neighbors on grid
sce <- buildSpatialGraph(sce, img_id = "ImageNb",
                            coords=c("Location_Center_X", "Location_Center_Y"),     
                            type = "knn",
                            k = 8)
sce$metacluster <- as.factor(sce$metacluster)

# take subset for visualization
subset <- sce[,sce$ImageNb == 29]
plotSpatial(subset,
            img_id = "ImageNb",
            coords=c("Location_Center_X", "Location_Center_Y"),
            node_color_by = "metacluster",
            draw_edges = TRUE,
            colPairName = "knn_interaction_graph",
            directed = FALSE,
            nodes_first = FALSE)
```
```{r}
hex_codes2 <- hue_pal()(27)                             # Identify hex codes
show_col(hex_codes2)
```
#compute interactions between metaclusters
```{r}

interactions <- testInteractions(sce,
                        group_by = "ImageNb",
                        label = "metacluster",
                        method = "classic",
                        colPairName = "knn_interaction_graph")

interactions_ct <- interactions[,c("group_by","from_label","to_label","ct")]
interactions_per_image <- split(interactions_ct[,c("from_label","to_label","ct")],interactions_ct$group_by)

ct_matrix <- lapply(interactions_per_image, function(x){
  z <- as.matrix(subset(reshape(x, idvar="from_label",timevar = "to_label", direction = "wide"),select=-c(1)))
  z[is.na(z)] <- 0
  return (z)
})

```


```{r}
meta_clusters_name = c("B cell","T & B cells","T cell","Macrophage","T cell",
                 "Macrophage","Endothelial","Vimentin hi","Small circular","Small elongated",
                 "Fibronectin hi","Large elongated","SMA hi Vimentin hi","Hypoxic","Apoptotic",
                 "Proliferative","p53+ EGFR+","Basal CK","CK7+ CK hi Ecadh hi","CK7+",
                 "Epithelial low","CK lo HR lo","CK+ HR hi","CK+ HR+","CK+ HR lo",
                 "CK lo HR hi p53+","Myoepithelial")
col_fun <- colorRamp2(c(0,0.2,0.4,0.6,0.8,1),viridis(6))

ct_sum <- Reduce("+", ct_matrix)
rownames(ct_sum) <- meta_clusters_name
colnames(ct_sum) <- meta_clusters_name
#normalize values

norm_interaction <- (ct_sum-min(ct_sum))/(max(ct_sum) - min(ct_sum))

Heatmap(norm_interaction, cluster_rows = FALSE, cluster_columns = FALSE,col = col_fun,column_title = "Breast Cancer tissue",
                  heatmap_legend_param = list(title = "interaction strength", at = c(1,0,0.2,0.4,0.6,0.8),
                                                   labels = c("total overlap", "no overlap","0.2","0.4","0.6","0.8")))


write.matrix(norm_interaction, file="/Users/bp/data/cellular_automata_bio394/ct_interactions_knn8.csv",sep=",")
```
##count total frequency of cell type
```{r}
total_frq <- proportions(table(sce$metacluster))
total_freq <- as.matrix(total_frq)
write.matrix(total_freq, file="/Users/bp/data/cellular_automata_bio394/total_freq.csv",sep=",")

rownames(total_freq) <- meta_clusters_name
Heatmap(total_freq, cluster_rows = FALSE, cluster_columns = FALSE,column_title = "Total frequency per metacluster")
```