---
title: "Distance distribution"
author: "BrunoPalau"
date: "`r Sys.Date()`"
output: html_document
---

#Quantify Interaction distances between cells in breast cancer tissue to use it in generative model

##import libraries and breast cancer single cell experiment
```{r,include=FALSE}
library(MASS)
library(ComplexHeatmap)
library(imcdatasets)
library(imcRtools)
library(Giotto)

library(dplyr)
library(tibble)

library(scales)
library(ggplot2)

sce <- JacksonFischer2020Data(data_type = "sce")
```

##subset and build spatial graph
```{r}

subset <- sce[,sce$ImageNb == 29]

#use 8 neighbors to simulate nearest 8 neighbors on grid
subset <- buildSpatialGraph(subset, img_id = "ImageNb",
                            coords=c("Location_Center_X", "Location_Center_Y"),     
                            type = "knn",
                            k = 8)
subset$metacluster <- as.factor(subset$metacluster)

# take subset for visualization
plotSpatial(subset,
            img_id = "ImageNb",
            coords=c("Location_Center_X", "Location_Center_Y"),
            node_color_by = "metacluster",
            draw_edges = TRUE,
            colPairName = "knn_interaction_graph",
            directed = FALSE,
            nodes_first = FALSE)
```

```{r}
# paste metacluster to cell id to extract after graph building with giotto

new_cell_id <- paste0(sce$id,"/",sce$metacluster)
colnames(sce) <- new_cell_id
```


```{r}
# create one giotto object with whole dataset to use as storage of single networks
raw_exprs <- assay(sce,"exprs")
spatial_locs <- data.frame(x_location=sce$Location_Center_X,y_location=sce$Location_Center_Y)
cell_metadata <- sce$metacluster
custom_expr <- assay(sce,"exprs")
# create giotto-object
giotto_object <- createGiottoObject(raw_exprs = raw_exprs,
                                  spatial_locs = spatial_locs,
                                  cell_metadata = cell_metadata,
                                  custom_expr = custom_expr)
```

```{r, include=FALSE}
# compute graphs for each image independently 
for (img_nr in unique(sce$ImageNb)){
  # take cells of one image
  cells <- sce[,sce$ImageNb==img_nr]
    
  # prepare giotto-object with cells
  raw_exprs <- assay(cells,"exprs")
  spatial_locs <- data.frame(x_location=cells$Location_Center_X,y_location=cells$Location_Center_Y)
  cell_metadata <- cells$metacluster
  custom_expr <- assay(cells,"exprs")
  # create giotto-object
  giotto_mini <- createGiottoObject(raw_exprs = raw_exprs,
                                    spatial_locs = spatial_locs,
                                    cell_metadata = cell_metadata,
                                    custom_expr = custom_expr)

  giotto_mini = createSpatialKNNnetwork(giotto_mini,k=8,name="knn_network")
    
  giotto_object@spatial_network$knn_network$networkDT <- rbind(giotto_object@spatial_network$knn_network$networkDT,
                                                              giotto_mini@spatial_network$knn_network$networkDT)
}


```

```{r}
# giotto_object = createSpatialKNNnetwork(giotto_object,k=8,name="knn_network")

graph_df <- giotto_object@spatial_network$knn_network$networkDT
```

```{r}
graph_df$meta_from <- sapply(strsplit(graph_df$from,"/"),"[[",2)
graph_df$meta_to <- sapply(strsplit(graph_df$to,"/"),"[[",2)
graph_df$meta_both <- paste0(sapply(strsplit(graph_df$from,"/"),"[[",2),"-",sapply(strsplit(graph_df$to,"/"),"[[",2))

```


```{r}
# make plot for assumption on how distances between cells are distributed -> normally distributed
ggplot(graph_df,aes(x=distance)) + 
  geom_histogram(bins=100)

```

```{r,fig.width = 10,fig.height=10}

# is there difference for celltypes?
ggplot(graph_df,aes(x=distance,fill=meta_from)) + 
  geom_histogram(bins=100,alpha=0.9)

ggplot(graph_df,aes(x=distance,fill=meta_from)) + 
  geom_density(alpha=0.8,lwd=0.8,adjust=0.5)+
  facet_wrap(~meta_from)

ggplot(graph_df,aes(x=meta_from,y=distance,fill=meta_from))+
  geom_boxplot()

anova_from <- lm(distance ~ meta_from,graph_df)
summary(anova_from)
anova(anova_from)
```

```{r}
d <- as.data.frame(summary(anova_from)$coef)

export_df <- d%>%
  select(Estimate,"Std. Error")

# change name of intercept
names <- rownames(export_df)
names[1] <- "1"
rownames(export_df) <- names
rownames(export_df) <- sub(".*from","",rownames(export_df))

# add intercept to value of all others
export_df$Estimate[2:length(export_df$Estimate)] <- sapply(export_df$Estimate[2:length(export_df$Estimate)],function(x){
  return (export_df$Estimate[[1]] + x)
})

export_df<- rownames_to_column(export_df,var="metacluster")
export_df_ordered <- export_df[order(as.numeric(export_df$metacluster)),]


# save df
write.csv(export_df_ordered,"/Users/bp/data/cellular_automata_bio394/distance_matrix.csv",row.names = FALSE)

```


```{r,fig.width = 10,fig.height=10}

# to and from are different even tho undirected graph as knn not symmetrical
ggplot(graph_df,aes(x=distance,fill=meta_to)) + 
  geom_histogram(bins=100,alpha=0.9)

ggplot(graph_df,aes(x=distance,fill=meta_to)) + 
  geom_density(alpha=0.8,lwd=0.8,adjust=0.5)+
  facet_wrap(~meta_to)

ggplot(graph_df,aes(x=meta_to,y=distance,fill=meta_to))+
  geom_boxplot()

anova_to <- lm(distance ~ meta_to,graph_df)
summary(anova_to)
anova(anova_to)
```

```{r}
anova_comb <- lm(distance ~ meta_to + meta_from,graph_df)
summary(anova_comb)
anova(anova_comb)
```


```{r,fig.width = 10,fig.height=10}

# is there difference for celltypes?
graph_df$meta_both <- as.factor(unlist(graph_df$meta_both))
ggplot(graph_df,aes(x=distance,fill=meta_both)) + 
  geom_histogram(bins=100,alpha=0.9)+
  theme(legend.position = "none")

ggplot(graph_df,aes(x=distance,fill=meta_both)) + 
  geom_density(alpha=0.8,lwd=0.8,adjust=0.5)+
  facet_wrap(~meta_both)



anova_both <- lm(distance ~ meta_both,graph_df)
summary(anova_both)
anova(anova_both)
```
