---
title: "spatial_distribution"
author: "BrunoPalau"
date: "`r Sys.Date()`"
output: html_document
---
#Analyse the spatial distribution of cells in breast cancer tissue

##import libraries and breast cancer single cell experiment
```{r,include=FALSE}
library(MASS)
library(ComplexHeatmap)
library(imcdatasets)
library(imcRtools)
library(Giotto)

library(dplyr)
library(ash)

library(viridis)
library(scales)
library(ggplot2)
library(cowplot)

sce <- JacksonFischer2020Data(data_type = "sce")
```

##subset and build spatial graph
```{r}

subset <- sce[,sce$ImageNb == 29]

#use 8 neighbors to simulate nearest 8 neighbors on grid
subset <- buildSpatialGraph(subset, img_id = "ImageNb",
                            coords=c("Location_Center_X", "Location_Center_Y"),     
                            type = "knn",
                            k = 8)
subset$metacluster <- as.factor(subset$metacluster)

# take subset for visualization
plotSpatial(subset,
            img_id = "ImageNb",
            coords=c("Location_Center_X", "Location_Center_Y"),
            node_color_by = "metacluster",
            draw_edges = TRUE,
            colPairName = "knn_interaction_graph",
            directed = FALSE,
            nodes_first = FALSE)
```


```{r}
img_nr_list <- list(29,30,31)
spatial_df_list <- list()
for (img_nr in img_nr_list){
  subset <- subset <- sce[,sce$ImageNb == img_nr]

  spatial_df <- data.frame(x = subset$Location_Center_X, y = subset$Location_Center_Y, metacluster = subset$metacluster)
  
  spatial_df_list <- append(spatial_df_list,list(spatial_df))
}
```


```{r, fig.width = 20,fig.height=20}
# spatial distribution seems to be binomial in the sense that it is either empty or 
list_total_plot <- list()
list_meta_plot <- list()

for (spatial_df in spatial_df_list){
  total_plot <- ggplot(spatial_df,aes(x=x,y=y))+
    geom_bin2d(bins=50)+
    scale_fill_continuous(type="viridis")+
    theme_bw()
  
  meta_plot <- ggplot(spatial_df,aes(x=x,y=y))+
    geom_bin2d(bins=50)+
    scale_fill_continuous(type="viridis")+
    facet_wrap(~metacluster)+
    theme_bw()
  
  list_total_plot <- append(list_total_plot,list(total_plot))
  list_meta_plot <- append(list_meta_plot,list(meta_plot))
}

plot_grid(plotlist = list_total_plot)
plot_grid(plotlist = list_meta_plot)

# specially cluster 25 and 18 seems to have some kind of spatial distributions

# todo: get bins calculated and make histogram of that for multiple images in dataset
# todo: make a colored version of this to see if one metacluster is overrepresented in 
```

```{r}
# plot histogram of bin count on 2d to see if cells are clustered

bins_vector <- c()
for (img_nr in unique(sce$ImageNb)){
  image_sce <- sce[,sce$ImageNb==img_nr]
  bins <- bin2(cbind(image_sce$Location_Center_X,image_sce$Location_Center_Y),nbin=c(10,10))
  bins_vector <- c(bins_vector,c(bins$nc))
}

bins_df <- data.frame(values = bins_vector)


ggplot(bins_df,aes(x=values))+
  geom_histogram(nbins=50)+
  theme_bw()


```
```{r,fig.width = 12,fig.height=12}
# to binning analysis metacluster specific

list_bins_res <- vector(mode="list",length = length(unique(sce$metacluster)))
bins_vector <- c()
for (img_nr in unique(sce$ImageNb)){
  image_sce <- sce[,sce$ImageNb==img_nr]
  for (metacluster in unique(image_sce$metacluster)){
    meta_sce <- image_sce[,image_sce$metacluster==metacluster]
    
    bins <- bin2(cbind(meta_sce$Location_Center_X,meta_sce$Location_Center_Y),nbin=c(30,30))
    meta_bins <- c(bins$nc)
    
    list_bins_res[[metacluster]] <- c(list_bins_res[[metacluster]],meta_bins)
  }
}

bins_res_vector <- unlist(list_bins_res)
a <- lapply(seq_along(list_bins_res),function(i){
  meta_seq <- rep(i,length(list_bins_res[[i]]))
  return (meta_seq)
})
meta_cluster_vector <- unlist(a)

df <- data.frame(bins_values = bins_res_vector, metacluster = meta_cluster_vector)

ggplot(df,aes(x=bins_values))+
  geom_histogram(nbins=20)+
  theme_bw()+
  facet_wrap(~metacluster)
  

```